// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tswopzusnqbyakkjkefv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzd29wenVzbnFieWFra2prZWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzQ5ODgsImV4cCI6MjA2NTg1MDk4OH0.Agm59pr6JFeakBUjY8ha2At674tP9l91fXG2RWQHlh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);